baseURL = "https://darrenclark.ca/"
languageCode = "en-us"
title = "Darren Clark"
pygmentsCodefences = true

[params]
  mainSections = ["articles"]

[permalinks]
  articles = "/:title"

[markup.goldmark.renderer]
unsafe= true
