baseURL = "https://darrenclark.ca/"
languageCode = "en-us"
title = "Darren Clark"

[params]
  mainSections = ["articles"]

[permalinks]
  articles = "/:title"

[markup.goldmark.renderer]
unsafe= true

[markup.highlight]
noClasses=false
guessSyntax=false
