name: Build Site

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: npm install

      - name: Install Hugo
        run: |
          cd /tmp
          curl -L -o hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v0.92.1/hugo_0.92.1_Linux-64bit.tar.gz
          tar -xzf hugo.tar.gz
          mv hugo /usr/local/bin

      - name: Prep output directory
        run: |
          git branch gh-pages origin/gh-pages
          git clone --branch=gh-pages . /tmp/out
          cp ./CNAME /tmp/out

      - name: Build site
        run: bin/build -d /tmp/out

      - name: Commit changes
        run: |
          cd /tmp/out
          git add .
          git commit -m 'Update gh-pages'
          # pushes back to main checkout
          git push

      - run: git push origin gh-pages:gh-pages
